### ISSUE TITLE
Can't use base64 image for icon

### ISSUE THREAD

**Issue by DenisD3D** [makenotion/notion-sdk-js#193]
**Describe the bug**
When creating a new page in a database, you can't set the icon to a base64 image. It work fine using an https link
```js
icon: {
  type: "external",
  external : {
      //With base64 encoded image (in this case a pink pixel) => { code: 'validation_error', message: 'Invalid page icon URL.' }
      url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HgAGgwJ/lK3Q6wAAAABJRU5ErkJggg=="
      //With https link the icon is set correctly
      url: "https://img.icons8.com/ios-filled/250/000000/mac-os.png"
  }
},
```
When using the Notion Desktop app i have no issue setting my icon to a base64 image

**To Reproduce**
Node version: 14.13.0
Notion JS library version: 0.3.2

Create a page in a database with the following icon settings : 
```js
icon: {
    type: "external",
    external : {
        url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HgAGgwJ/lK3Q6wAAAABJRU5ErkJggg=="
    }
},
```

The following error is returned:
```
@notionhq/client warn: request fail { code: 'validation_error', message: 'Invalid page icon URL.' }
(node:12668) UnhandledPromiseRejectionWarning: APIResponseError: Invalid page icon URL.
    at Object.buildRequestError (REMOVED\node_modules\@notionhq\client\build\src\errors.js:162:16)
    at Client.request (REMOVED\node_modules\@notionhq\client\build\src\Client.js:278:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async REMOVED
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not ha
ndled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejectio
n id: 1)
(node:12668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
The API / JS lib should allow base64 image as the Desktop App do.

**Screenshots**
Nothing created through the api
Work in the desktop app: 
![image](https://user-images.githubusercontent.com/35769613/133858535-78890b74-add7-4af6-b384-61ac6bd26e0a.png)

Denis

**Comment by cwang314** [comment]
Hi @DenisD3D, we don't yet support uploading image files in the API. Closing because this isn't an issue with the SDK per se; however, you can submit bugs and feature requests through Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.
